name: house_prices_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - pandas>=2.0.0
      - numpy>=1.24.0
      - scikit-learn>=1.3.0
      - mlflow==2.19.0
      - dagshub>=0.3.0
